export const songGenres = [
    "Blues", 
    "Classical", 
    "Country", 
    "EDM", 
    "Hip-Hop/Rap", 
    "Indie", 
    "Jazz", 
    "Metal", 
    "Pop", 
    "R&B", 
    "Reggae", 
    "Rock",
    "Ballab",
]